# @package _group_

common:
  fp16: true
  log_format: json
  log_interval: 200
  tensorboard_logdir: tblog
  seed: 1337

checkpoint:
  #---wsy fix------------------
  # save_interval: 5
  save_interval_updates: 25000
  #----------------------------

  keep_interval_updates: 1
  no_epoch_checkpoints: true
  best_checkpoint_metric: wer

distributed_training:
  ddp_backend: c10d
  find_unused_parameters: true
  distributed_world_size: 1
  distributed_port: 29671
  nprocs_per_node: 8

task:
  _name: hubert_pretraining
  
  # tsv 根目录 注意
  data: /your/data_dir
  fine_tuning: true
  
  # ltr/unit 根目录
  label_dir: /your/label_dir
  normalize: false  # must be consistent with pre-training

  # 任务选择
  labels: ["ltr"] # asr or kws
  # labels: ["unit"] # sn

  single_target: true

dataset:
  # num_workers: 0
  num_workers: 4 # wsy fix 增加占用显存的地方 

  max_tokens: 3200000
  validate_after_updates: ${model.freeze_finetune_updates}

  validate_interval: 5
  # validate_interval: 100

  # wsy:设置tsv名字的地方
  # 注意
  train_subset: train
  valid_subset: valid

criterion:
  _name: ctc
  zero_infinity: true

optimization:
  #---wsy fix---------
  # max_update: 25000
  # lr: [2e-5]
  max_update: 9600000
  # 学习率设置
  # lr: [0.0000005] # -7
  # lr: [0.000005] # -6
  lr: [0.00005] # -5
  # lr: [0.001] # 没用
  #-------------------
  sentence_avg: true
  update_freq: [1]

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-08

lr_scheduler:
  _name: tri_stage
  #---wsy fix---------
  # warmup_steps: 8000
  warmup_steps: 32000
  #-------------------
  hold_steps: 0
  decay_steps: 72000
  final_lr_scale: 0.05

model:
  _name: hubert_ctc
  
  # 使用的预训练hubert模型 注意
  w2v_path: /your/pretrain_hubert_path

  apply_mask: true
  mask_selection: static
  mask_length: 10
  mask_other: 0
  mask_prob: 0.75
  mask_channel_selection: static
  mask_channel_length: 64
  mask_channel_other: 0
  mask_channel_prob: 0.5
  layerdrop: 0.1
  dropout: 0.0
  activation_dropout: 0.1
  attention_dropout: 0.0
  feature_grad_mult: 0.0
  freeze_finetune_updates: 10000

hydra:
  job:
    config:
      override_dirname:
        kv_sep: '-'
        item_sep: '__'
        exclude_keys:
          - run
          - task.data
          - task.label_dir
          - model.w2v_path
          - dataset.train_subset
          - dataset.valid_subset
          - criterion.wer_kenlm_model
          - criterion.wer_lexicon
    config_name: "base_10h" # wsy add
  run:
    # 注意 放置ckpt和log的地方
    dir: /your/checkpoints_dir
  sweep:
    dir: [PB-DSR DIR]/checkpoints
    subdir: ${hydra.job.config_name}__${hydra.job.override_dirname}